services:
  db:
    image: mysql:8.0.26
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: digitalsupport
      MYSQL_USER: digitalsupport
      MYSQL_PASSWORD: Digital@support
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
    restart: always
    volumes:
      - /var/backup/digitalsupport:/var/lib/mysql
    networks:
      - application

  migration:
    image: digital_support:latest
    profiles: [initialize]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate"
    networks:
      - application

  app:
    image: digital_support:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 172.16.15.131:8000:8000
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
    networks:
      - application

networks:
  application: