# Generated by Django 5.1.1 on 2024-09-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsDigital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(max_length=250),
        ),
    ]
