# Generated by Django 5.1.1 on 2024-10-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsDigital', '0003_smslog_user_alter_smslog_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='sent_at',
            field=models.DateTimeField(),
        ),
    ]
